name: CI/CD Pipeline for Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21 # Or your JDK version
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # Use Temurin for a reliable OpenJDK distribution

      - name: Cache Maven local repository # Optional but good for performance
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven # Or Gradle if you use Gradle
        run: ./mvnw clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t students-app:latest .
          docker tag students-app:latest ${{ secrets.DOCKER_USERNAME }}/students-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/students-app:latest